// Weitere heimische Arten — ausgelagert aus species.js, um die Datei unter 500 Zeilen zu halten.
// Gleiches Format wie der Haupt-Katalog: fest verbaute Ruf-Bedeutung + Steckbrief, ohne
// Gemini/Wikipedia nötig. Wird in species.js in den SPECIES-Katalog gemischt.

const BIRD = '<path d="M16 7c1.5 0 3 1 3 3 0 3-3 5-3 5l-7 1c-3 0-5-2-5-4 0-1 .5-2 2-2"/><path d="M16 7l4-2-2 3"/><circle cx="15" cy="8.5" r=".8" fill="currentColor" stroke="none"/><path d="M9 15l-2 4M12 16l-1 4"/>';
const DEER = '<path d="M7 14c0-3 2-6 5-6s5 3 5 6-2 5-5 5-5-2-5-5z"/><path d="M8 9l-1-4 3 3M16 9l1-4-3 3"/>';
const GREEN = ['#0e5840', '#0a4733'];
const ROSE  = ['#3a1420', '#2e0f18'];
const B = { icon: BIRD, grad: GREEN, accent: '#a3e635' };
const M = { icon: DEER, grad: ROSE, accent: '#fb7185' };

export const EXTRA_SPECIES = {
  tannenmeise: { key:'tannenmeise', name:'Tannenmeise', sci:'Periparus ater', rarity:'common', ...B,
    meaning:'Ein hohes, hastiges „Si-si-düh" ist <b style="color:var(--ink)">Reviergesang</b> — typisch für Nadelwälder.',
    steckbrief:'10–11 cm · kleinste heimische Meise · spezialisiert auf Nadelwald, versteckt Samen als Wintervorrat.' },
  haubenmeise: { key:'haubenmeise', name:'Haubenmeise', sci:'Lophophanes cristatus', rarity:'common', ...B,
    meaning:'Ein schnurrender Triller „Zi-zi-zürrrr" ist <b style="color:var(--ink)">Kontaktruf</b> — die Federhaube macht sie unverwechselbar.',
    steckbrief:'11–12 cm · spitze Federhaube · fast nur in naturnahen Nadel- und Mischwäldern.' },
  sumpfmeise: { key:'sumpfmeise', name:'Sumpfmeise', sci:'Poecile palustris', rarity:'common', ...B,
    meaning:'Ein scharfes „Pitschü" ist <b style="color:var(--ink)">Kontaktruf</b> — trotz des Namens eher in Laubwäldern als im Sumpf.',
    steckbrief:'11–12 cm · schwarze Kopfkappe, kein heller Nackenfleck · der Kohlmeise ähnlich, aber kleiner.' },
  weidenmeise: { key:'weidenmeise', name:'Weidenmeise', sci:'Poecile montanus', rarity:'common', ...B,
    meaning:'Ein nasales, gedehntes „Däh-däh-däh" ist <b style="color:var(--ink)">Warnruf</b> — der Sumpfmeise zum Verwechseln ähnlich, aber matter im Klang.',
    steckbrief:'12–13 cm · zimmert eigene Bruthöhlen in morschem Holz · feuchte Wälder mit Totholz.' },
  schwanzmeise: { key:'schwanzmeise', name:'Schwanzmeise', sci:'Aegithalos caudatus', rarity:'common', ...B,
    meaning:'Hohe, perlende „Si-si-si"-Rufe halten den Trupp <b style="color:var(--ink)">in Kontakt</b> — Schwanzmeisen ziehen fast immer in kleinen Gruppen umher.',
    steckbrief:'13–15 cm, davon die Hälfte Schwanz · rundlich, watteballartig · baut kunstvolle, flechtenverkleidete Nester.' },
  wintergoldhaehnchen: { key:'wintergoldhaehnchen', name:'Wintergoldhähnchen', sci:'Regulus regulus', rarity:'common', ...B,
    meaning:'Ein extrem hoher, fast an der Hörgrenze liegender Triller „Sih-sih-sih" ist <b style="color:var(--ink)">Reviergesang</b>.',
    steckbrief:'9 cm · kleinster Vogel Europas · orange-gelber Scheitelstreif, fast nur in Nadelbäumen.' },
  sommergoldhaehnchen: { key:'sommergoldhaehnchen', name:'Sommergoldhähnchen', sci:'Regulus ignicapilla', rarity:'common', ...B,
    meaning:'Ähnlich hoher Triller wie beim Wintergoldhähnchen, endet aber mit einem kleinen Schnörkel — <b style="color:var(--ink)">Reviergesang</b>.',
    steckbrief:'9–10 cm · schwarzer Augenstreif, etwas bunter als das Wintergoldhähnchen · auch in Mischwäldern.' },
  gartenbaumlaeufer: { key:'gartenbaumlaeufer', name:'Gartenbaumläufer', sci:'Certhia brachydactyla', rarity:'common', ...B,
    meaning:'Ein scharfes „Tit-tit-tit-türooi" ist <b style="color:var(--ink)">Reviergesang</b> — meist spiralförmig stammaufwärts kletternd vorgetragen.',
    steckbrief:'12–13 cm · gebogener Schnabel, klettert spiralig an Stämmen hoch · Parks und Gärten.' },
  waldbaumlaeufer: { key:'waldbaumlaeufer', name:'Waldbaumläufer', sci:'Certhia familiaris', rarity:'common', ...B,
    meaning:'Ein hoher, dünner Gesang mit klarem Schlusstriller ist <b style="color:var(--ink)">Reviergesang</b> — dem Gartenbaumläufer sehr ähnlich, aber reiner Waldvogel.',
    steckbrief:'12–13 cm · bevorzugt naturnahe, ältere Nadel- und Mischwälder gegenüber dem Gartenbaumläufer.' },

  gartengrasmuecke: { key:'gartengrasmuecke', name:'Gartengrasmücke', sci:'Sylvia borin', rarity:'common', ...B,
    meaning:'Ein gleichmäßig schwätzender, eher leiser Gesang ohne markante Schlussstrophe ist <b style="color:var(--ink)">Reviergesang</b>.',
    steckbrief:'14 cm · unauffällig graubraun, keine Kopfzeichnung · dichtes Gebüsch, oft versteckt singend.' },
  dorngrasmuecke: { key:'dorngrasmuecke', name:'Dorngrasmücke', sci:'Sylvia communis', rarity:'common', ...B,
    meaning:'Ein kratzig-schnatternder, kurzer Gesang, oft im kurzen Singflug vorgetragen — <b style="color:var(--ink)">Reviergesang</b>.',
    steckbrief:'14 cm · rostbraune Flügel, grauer Kopf beim Männchen · Hecken und Brachflächen.' },
  klappergrasmuecke: { key:'klappergrasmuecke', name:'Klappergrasmücke', sci:'Sylvia curruca', rarity:'common', ...B,
    meaning:'Ein leises Schwätzen, das in ein hartes, klapperndes Rasseln übergeht — <b style="color:var(--ink)">Reviergesang</b>, namensgebend.',
    steckbrief:'13 cm · kleinste heimische Grasmücke, dunkle „Maske" ums Auge · Hecken und Gärten.' },
  waldlaubsaenger: { key:'waldlaubsaenger', name:'Waldlaubsänger', sci:'Phylloscopus sibilatrix', rarity:'rare', ...B,
    meaning:'Ein beschleunigter, schwirrender Triller, der wie eine fallende Münze klingt — markanter <b style="color:var(--ink)">Reviergesang</b>.',
    steckbrief:'12 cm · gelbgrüne Oberseite, reinweißer Bauch · bevorzugt hallenartige, unterholzarme Buchenwälder.' },

  kernbeisser: { key:'kernbeisser', name:'Kernbeißer', sci:'Coccothraustes coccothraustes', rarity:'rare', ...B,
    meaning:'Ein scharfes, metallisches „Zix" ist meist der einzige Hinweis — der eigentliche <b style="color:var(--ink)">Gesang</b> ist leise und unauffällig.',
    steckbrief:'18 cm · massiver Schnabel, kann Kirschkerne knacken · scheu, hält sich oft im Kronenbereich auf.' },
  bluthaenfling: { key:'bluthaenfling', name:'Bluthänfling', sci:'Linaria cannabina', rarity:'common', ...B,
    meaning:'Ein zwitscherndes, abwechslungsreiches Geplauder mit nasalen Tönen ist <b style="color:var(--ink)">Reviergesang</b>.',
    steckbrief:'13–14 cm · Männchen mit roter Brust im Brutkleid · offenes Gelände mit Hecken, Heiden.' },
  goldammer: { key:'goldammer', name:'Goldammer', sci:'Emberiza citrinella', rarity:'common', ...B,
    meaning:'Der bekannte Sing-Rhythmus „Wie-wie-wie-hab-ich-dich-lieb" ist <b style="color:var(--ink)">Reviergesang</b> des Männchens.',
    steckbrief:'16–17 cm · leuchtend gelber Kopf beim Männchen · Feldraine, Hecken, Waldränder.' },
  rohrammer: { key:'rohrammer', name:'Rohrammer', sci:'Emberiza schoeniclus', rarity:'common', ...B,
    meaning:'Ein kurzes, abgehacktes „Zip-zip-zip-zirrr" ist <b style="color:var(--ink)">Reviergesang</b>, oft von einem Schilfhalm aus vorgetragen.',
    steckbrief:'15 cm · Männchen mit schwarzem Kopf und weißem Bartstreif · Schilf- und Röhrichtzonen.' },

  feldlerche: { key:'feldlerche', name:'Feldlerche', sci:'Alauda arvensis', rarity:'common', ...B,
    meaning:'Ein anhaltender, perlender Gesang im Steigflug, oft minutenlang ohne Pause — <b style="color:var(--ink)">Reviergesang</b> hoch über dem Feld.',
    steckbrief:'18–19 cm · unscheinbar braun, kleine Federhaube · offene Feldflur, Bestand stark rückläufig.' },
  heidelerche: { key:'heidelerche', name:'Heidelerche', sci:'Lullula arborea', rarity:'rare', ...B,
    meaning:'Ein wehmütiger, abfallender Triller „Lülülülü" ist <b style="color:var(--ink)">Reviergesang</b>, oft schon vor Sonnenaufgang zu hören.',
    steckbrief:'15 cm · kürzerer Schwanz als die Feldlerche · lichte Wälder, Heiden, Truppenübungsplätze.' },
  wiesenpieper: { key:'wiesenpieper', name:'Wiesenpieper', sci:'Anthus pratensis', rarity:'common', ...B,
    meaning:'Ein dünnes „Ist-ist-ist", das in einen Trillergesang im Sinkflug übergeht — <b style="color:var(--ink)">Reviergesang</b>.',
    steckbrief:'14–15 cm · unscheinbar gestreift · feuchtes Grünland und Moore.' },
  baumpieper: { key:'baumpieper', name:'Baumpieper', sci:'Anthus trivialis', rarity:'common', ...B,
    meaning:'Startet von einer Baumspitze, singt im Sinkflug mit ausgebreiteten Flügeln und endet auf einer Sitzwarte — <b style="color:var(--ink)">Reviergesang</b>.',
    steckbrief:'15 cm · dem Wiesenpieper ähnlich, aber Waldränder statt offener Wiesen.' },
  bachstelze: { key:'bachstelze', name:'Bachstelze', sci:'Motacilla alba', rarity:'common', ...B,
    meaning:'Ein helles „Zi-witt" im wippenden Flug ist <b style="color:var(--ink)">Kontaktruf</b> — der ständig wippende Schwanz ist namensgebend für die Gattung.',
    steckbrief:'18 cm · schwarz-weiß-grau, ständig wippender Schwanz · Nähe von Wasser und Gebäuden.' },
  gebirgsstelze: { key:'gebirgsstelze', name:'Gebirgsstelze', sci:'Motacilla cinerea', rarity:'rare', ...B,
    meaning:'Ein scharfes „Zit-zit" ist <b style="color:var(--ink)">Kontaktruf</b> — meist an schnell fließenden, klaren Bächen zu hören.',
    steckbrief:'18–19 cm · leuchtend gelber Bauch, sehr langer Schwanz · steinige Bäche und Wehre, auch in der Eifel.' },

  rotdrossel: { key:'rotdrossel', name:'Rotdrossel', sci:'Turdus iliacus', rarity:'rare', ...B,
    meaning:'Ein dünnes, gezogenes „Sih" im nächtlichen Zugflug ist <b style="color:var(--ink)">Zugruf</b> — als Brutvogel in Deutschland selten.',
    steckbrief:'21 cm · rostroter Fleck an der Flanke, heller Überaugenstreif · meist nur als Wintergast/Durchzügler.' },

  rotmilan: { key:'rotmilan', name:'Rotmilan', sci:'Milvus milvus', rarity:'rare', ...B,
    meaning:'Ein hohes, miauendes „Hiäh-hiäh-hiäh" ist <b style="color:var(--ink)">Reviermarkierung</b> im eleganten Gleitflug mit gegabeltem Schwanz.',
    steckbrief:'175–195 cm Spannweite · tief gegabelter rostroter Schwanz · Deutschland beherbergt den Großteil des Weltbestands.' },
  schwarzmilan: { key:'schwarzmilan', name:'Schwarzmilan', sci:'Milvus migrans', rarity:'rare', ...B,
    meaning:'Ein wieherndes, zitterndes „Wididididi" ist <b style="color:var(--ink)">Reviermarkierung</b> — oft in der Nähe von Gewässern und Mülldeponien.',
    steckbrief:'Spannweite über 1,5 m · schwächer gegabelter Schwanz als der Rotmilan · Flussauen und Seen.' },
  sperber: { key:'sperber', name:'Sperber', sci:'Accipiter nisus', rarity:'rare', ...B,
    meaning:'Ein scharfes, schnelles „Ki-ki-ki-ki" nahe am Horst ist <b style="color:var(--ink)">Warn- oder Erregungsruf</b> — meist nur kurz, sonst ein stiller Jäger.',
    steckbrief:'Männchen deutlich kleiner als Weibchen · jagt Kleinvögel im schnellen Überraschungsflug durchs Unterholz.' },
  habicht: { key:'habicht', name:'Habicht', sci:'Accipiter gentilis', rarity:'rare', ...B,
    meaning:'Ein lautes, kreischendes „Gick-gick-gick" am Horst ist <b style="color:var(--ink)">Warnruf</b> — sonst meist lautlos und heimlich unterwegs.',
    steckbrief:'Spannweite bis 1,3 m · größter heimischer Habichtartiger · gewandter Jäger in dichtem Wald.' },
  wanderfalke: { key:'wanderfalke', name:'Wanderfalke', sci:'Falco peregrinus', rarity:'rare', ...B,
    meaning:'Ein hartes, schnelles „Kjäk-kjäk-kjäk" nahe am Horst ist <b style="color:var(--ink)">Warnruf</b> — schnellstes Tier der Welt im Sturzflug.',
    steckbrief:'Stoßflug über 300 km/h · brütet heute auch an hohen Gebäuden und Kirchtürmen, einst vom Aussterben bedroht.' },
  baumfalke: { key:'baumfalke', name:'Baumfalke', sci:'Falco subbuteo', rarity:'rare', ...B,
    meaning:'Ein hohes, schnelles „Kikiki" ist <b style="color:var(--ink)">Erregungsruf</b> — ein sichelflügeliger Jäger, der Libellen und Schwalben im Flug fängt.',
    steckbrief:'30–35 cm · schlank, sichelförmige Flügel wie ein großer Mauersegler · Zugvogel.' },
  schleiereule: { key:'schleiereule', name:'Schleiereule', sci:'Tyto alba', rarity:'rare', ...B,
    meaning:'Ein lang gezogenes, raues Fauchen oder Kreischen ist <b style="color:var(--ink)">Reviergesang</b> — kein klassisches "Uhu", eher unheimlich-schrill.',
    steckbrief:'33–35 cm · herzförmiger weißer Gesichtsschleier · brütet oft in Scheunen und Kirchtürmen.' },
  steinkauz: { key:'steinkauz', name:'Steinkauz', sci:'Athene noctua', rarity:'rare', ...B,
    meaning:'Ein klagendes „Guick" oder ein melodisches „Wuid-wuid" ist <b style="color:var(--ink)">Reviergesang</b> — auch tagsüber gelegentlich aktiv.',
    steckbrief:'21–23 cm · kleine, gedrungene Eule mit langen Beinen · Streuobstwiesen, stark gefährdet.' },
  uhu: { key:'uhu', name:'Uhu', sci:'Bubo bubo', rarity:'rare', ...B,
    meaning:'Ein tiefes, weithin hörbares „Buho" ist <b style="color:var(--ink)">Reviergesang</b> des Männchens — größte heimische Eule.',
    steckbrief:'Spannweite bis 1,7 m · auffällige Federohren, orangerote Augen · Felsen und Steinbrüche.' },

  kleinspecht: { key:'kleinspecht', name:'Kleinspecht', sci:'Dryobates minor', rarity:'rare', ...B,
    meaning:'Ein hohes, sich beschleunigendes Trommeln, leiser und länger als bei größeren Spechten — <b style="color:var(--ink)">Reviermarkierung</b>.',
    steckbrief:'14–15 cm · kleinster heimischer Specht, etwa spatzengroß · oft hoch in dünnen Kronenästen.' },
  mittelspecht: { key:'mittelspecht', name:'Mittelspecht', sci:'Dendrocoptes medius', rarity:'rare', ...B,
    meaning:'Ein nasales, leierndes „Wä-wä-wä-wä" ist <b style="color:var(--ink)">Reviergesang</b> — trommelt im Gegensatz zu anderen Spechten kaum.',
    steckbrief:'20 cm · rote Kappe (nicht nur Nacken wie beim Buntspecht) · braucht alte, grobrindige Eichenwälder.' },

  stockente: { key:'stockente', name:'Stockente', sci:'Anas platyrhynchos', rarity:'common', ...B,
    meaning:'Das bekannte „Quaak-quaak-quaak" der Ente ist <b style="color:var(--ink)">Kontaktruf</b> des Weibchens; das Männchen ist meist leiser.',
    steckbrief:'58 cm · häufigste Ente Deutschlands · Männchen mit glänzend grünem Kopf.' },
  hoeckerschwan: { key:'hoeckerschwan', name:'Höckerschwan', sci:'Cygnus olor', rarity:'common', ...B,
    meaning:'Meist stumm, aber ein zischendes Fauchen ist <b style="color:var(--ink)">Drohverhalten</b>, wenn man dem Nest zu nahe kommt.',
    steckbrief:'Spannweite bis 2,4 m · oranger Schnabel mit schwarzem Höcker · größter heimischer Wasservogel.' },
  graureiher: { key:'graureiher', name:'Graureiher', sci:'Ardea cinerea', rarity:'common', ...B,
    meaning:'Ein heiseres, krächzendes „Kraahk" im Abflug ist <b style="color:var(--ink)">Warnruf</b> — sonst lauert er meist reglos am Ufer.',
    steckbrief:'Spannweite bis 1,75 m · steht oft regungslos im Flachwasser auf der Fischjagd.' },
  blaesshuhn: { key:'blaesshuhn', name:'Blässhuhn', sci:'Fulica atra', rarity:'common', ...B,
    meaning:'Ein hartes, kurzes „Pix" oder „Kik" ist <b style="color:var(--ink)">Kontaktruf</b> — territorial und oft streitlustig gegenüber Artgenossen.',
    steckbrief:'38 cm · komplett schwarz mit weißer Stirnplatte · Teiche und Seen mit Schilf.' },
  teichhuhn: { key:'teichhuhn', name:'Teichhuhn', sci:'Gallinula chloropus', rarity:'common', ...B,
    meaning:'Ein scharfes, näselndes „Kurrk" ist <b style="color:var(--ink)">Kontakt- oder Warnruf</b> aus dem Schilf.',
    steckbrief:'33 cm · roter Schnabelschild, weißer Schwanzfleck beim Schwimmen sichtbar · kleinere Teiche und Gräben.' },
  haubentaucher: { key:'haubentaucher', name:'Haubentaucher', sci:'Podiceps cristatus', rarity:'common', ...B,
    meaning:'Ein tiefes, krächzendes Knurren ist <b style="color:var(--ink)">Reviergesang</b> — bekannt für seinen aufwendigen "Pinguintanz" zur Balz.',
    steckbrief:'46–51 cm · auffällige dunkle Federohren · taucht für Fischjagd minutenlang.' },
  kanadagans: { key:'kanadagans', name:'Kanadagans', sci:'Branta canadensis', rarity:'common', ...B,
    meaning:'Ein lautes, trompetendes „Ah-honk" im Verbandsflug ist <b style="color:var(--ink)">Kontaktruf</b> der Gruppe.',
    steckbrief:'90–100 cm · schwarzer Hals mit weißer "Kinnbinde" · ursprünglich aus Nordamerika eingebürgert.' },
  graugans: { key:'graugans', name:'Graugans', sci:'Anser anser', rarity:'common', ...B,
    meaning:'Ein tiefes, schnatterndes „Gangg-ang-ang" ist <b style="color:var(--ink)">Kontaktruf</b> — Stammform aller Hausgänse.',
    steckbrief:'75–90 cm · komplett graubraun, oranger Schnabel · Seen, Flussauen, oft in großen Trupps.' },

  dohle: { key:'dohle', name:'Dohle', sci:'Coloeus monedula', rarity:'common', ...B,
    meaning:'Ein helles, metallisches „Kjak" oder „Tschäck" ist <b style="color:var(--ink)">Kontaktruf</b> — kleinste heimische Krähenart.',
    steckbrief:'33 cm · grauer Nacken, helle Augen · brütet in Kolonien an Türmen, Kirchen, alten Bäumen.' },
  saatkraehe: { key:'saatkraehe', name:'Saatkrähe', sci:'Corvus frugilegus', rarity:'common', ...B,
    meaning:'Ein raues „Kraah", heiserer als bei der Rabenkrähe, ist <b style="color:var(--ink)">Kontaktruf</b> in der Kolonie.',
    steckbrief:'46 cm · nackte, helle Schnabelbasis (Unterschied zur Rabenkrähe) · brütet in großen Baumkolonien.' },
  kolkrabe: { key:'kolkrabe', name:'Kolkrabe', sci:'Corvus corax', rarity:'rare', ...B,
    meaning:'Ein tiefes, glucksendes „Krrok-krrok" ist <b style="color:var(--ink)">Kontaktruf</b> — größter Singvogel der Welt, sehr klug.',
    steckbrief:'Spannweite bis 1,3 m · keilförmiger Schwanz im Flug · einst fast ausgerottet, heute wieder verbreitet.' },
  pirol: { key:'pirol', name:'Pirol', sci:'Oriolus oriolus', rarity:'rare', ...B,
    meaning:'Ein flötender, melodischer Ruf „Düdlü-djüo" ist <b style="color:var(--ink)">Reviergesang</b> — der Vogel selbst bleibt fast immer im dichten Laub verborgen.',
    steckbrief:'24 cm · Männchen leuchtend gelb-schwarz · scheuer Kronenbewohner lichter Laubwälder.' },
  neuntoeter: { key:'neuntoeter', name:'Neuntöter', sci:'Lanius collurio', rarity:'rare', ...B,
    meaning:'Ein schwätzender, oft andere Vogelstimmen imitierender Gesang ist <b style="color:var(--ink)">Reviergesang</b> — bekannt fürs Aufspießen von Beute an Dornen.',
    steckbrief:'17 cm · Männchen mit grauem Kopf und schwarzer Augenmaske · Hecken mit Dornsträuchern.' },

  mehlschwalbe: { key:'mehlschwalbe', name:'Mehlschwalbe', sci:'Delichon urbicum', rarity:'common', ...B,
    meaning:'Ein zwitscherndes Schwatzen im Flug ist <b style="color:var(--ink)">Kontaktgesang</b> — baut kugelige Lehmnester unter Dachvorsprüngen.',
    steckbrief:'13 cm · reinweißer Bürzel (Unterschied zur Rauchschwalbe) · brütet oft in Kolonien an Gebäuden.' },
  uferschwalbe: { key:'uferschwalbe', name:'Uferschwalbe', sci:'Riparia riparia', rarity:'rare', ...B,
    meaning:'Ein trockenes, schnarrendes Zwitschern ist <b style="color:var(--ink)">Kontaktruf</b> der Kolonie an Steilufern.',
    steckbrief:'12 cm · kleinste heimische Schwalbe, braunes Brustband · brütet in Erdhöhlen in Sand- und Kiesgruben.' },

  tuerkentaube: { key:'tuerkentaube', name:'Türkentaube', sci:'Streptopelia decaocto', rarity:'common', ...B,
    meaning:'Ein monotones, dreisilbiges „Gu-guu-gu" ist <b style="color:var(--ink)">Reviergesang</b>, oft vom Dach oder einer Antenne aus.',
    steckbrief:'32 cm · schlanker als die Ringeltaube, schwarzer Nackenring · eng an Siedlungen gebunden.' },
  hohltaube: { key:'hohltaube', name:'Hohltaube', sci:'Columba oenas', rarity:'rare', ...B,
    meaning:'Ein dumpfes, zweisilbiges „Hu-hu" ist <b style="color:var(--ink)">Reviergesang</b> aus einer Baumhöhle.',
    steckbrief:'33 cm · kleiner als die Ringeltaube, kein weißer Halsfleck · brütet in alten Spechthöhlen.' },

  braunkehlchen: { key:'braunkehlchen', name:'Braunkehlchen', sci:'Saxicola rubetra', rarity:'rare', ...B,
    meaning:'Ein kurzer, schwätzender Gesang von einer Halmspitze aus ist <b style="color:var(--ink)">Reviergesang</b> — stark gefährdet durch frühe Wiesenmahd.',
    steckbrief:'13 cm · heller Überaugenstreif, rostbraune Brust · extensiv genutzte Feuchtwiesen.' },
  schwarzkehlchen: { key:'schwarzkehlchen', name:'Schwarzkehlchen', sci:'Saxicola rubicola', rarity:'common', ...B,
    meaning:'Ein hartes „Tek-tek" wie zwei klackernde Steine ist <b style="color:var(--ink)">Warnruf</b> — sitzt gern exponiert auf Zaunpfählen.',
    steckbrief:'12–13 cm · Männchen mit schwarzem Kopf, weißem Halsfleck · Brachflächen und Wegränder.' },
  wasseramsel: { key:'wasseramsel', name:'Wasseramsel', sci:'Cinclus cinclus', rarity:'rare', ...B,
    meaning:'Ein knirschend-schwätzender Gesang, oft im Rauschen des Bachs kaum zu hören — <b style="color:var(--ink)">Reviergesang</b>, ganzjährig auch im Winter.',
    steckbrief:'18 cm · einziger heimischer Singvogel, der taucht und unter Wasser läuft · klare, schnelle Bäche, auch in der Eifel.' },

  hase: { key:'hase', name:'Feldhase', sci:'Lepus europaeus', rarity:'mammal', ...M,
    meaning:'Hasen sind meist lautlos; ein schrilles Schreien ist ein <b style="color:var(--ink)">Schmerz- oder Angstlaut</b> in akuter Gefahr, sonst selten zu hören.',
    steckbrief:'Bis 70 cm lang · dämmerungsaktiv · lebt oberirdisch in flachen Mulden, keine Baue wie das Kaninchen.' },
  eichhoernchen: { key:'eichhoernchen', name:'Eichhörnchen', sci:'Sciurus vulgaris', rarity:'mammal', ...M,
    meaning:'Ein heiseres Schimpfen und Fußtrommeln auf Ästen ist <b style="color:var(--ink)">Warnverhalten</b>, oft bei Bedrohung durch Greifvögel oder Katzen.',
    steckbrief:'20–25 cm Körperlänge · tagaktiv · Fellfarbe variiert von rotbraun bis fast schwarz.' },
  igel: { key:'igel', name:'Igel', sci:'Erinaceus europaeus', rarity:'mammal', ...M,
    meaning:'Schmatzende und schnaubende Laute beim Fressen sind normal; ein schrilles Quietschen während der Paarung im Frühsommer ist <b style="color:var(--ink)">Balzverhalten</b>.',
    steckbrief:'20–30 cm · nachtaktiv · hält von November bis März Winterschlaf.' },
  steinmarder: { key:'steinmarder', name:'Steinmarder', sci:'Martes foina', rarity:'mammal', ...M,
    meaning:'Ein heiseres Fauchen oder Kreischen ist <b style="color:var(--ink)">Droh- oder Paarungsverhalten</b> — oft erst an Schäden im Auto-Motorraum bemerkt.',
    steckbrief:'42–48 cm Körperlänge · weißer, gegabelter Kehlfleck · nachtaktiv, lebt oft siedlungsnah.' },
  baummarder: { key:'baummarder', name:'Baummarder', sci:'Martes martes', rarity:'mammal', ...M,
    meaning:'Ähnlich wie der Steinmarder meist still; ein kurzes Fauchen ist <b style="color:var(--ink)">Drohverhalten</b> bei Bedrohung.',
    steckbrief:'45–50 cm Körperlänge · gelblicher (statt weißer) Kehlfleck · reiner Waldbewohner, klettert exzellent.' },
  rotwild: { key:'rotwild', name:'Rothirsch', sci:'Cervus elaphus', rarity:'mammal', ...M,
    meaning:'Das laute, weithin hörbare Röhren in der Brunftzeit (September/Oktober) ist <b style="color:var(--ink)">Rivalenruf</b> der Hirsche um die Weibchen.',
    steckbrief:'Größtes heimisches Wildtier · Hirsche tragen ein jährlich neu wachsendes Geweih · dämmerungsaktiv.' },
  damwild: { key:'damwild', name:'Damhirsch', sci:'Dama dama', rarity:'mammal', ...M,
    meaning:'Ein tiefes, rülpsendes Röhren während der Brunft (Oktober) ist <b style="color:var(--ink)">Rivalenruf</b>, dunkler und kürzer als beim Rothirsch.',
    steckbrief:'Schaufelförmiges Geweih beim Hirsch · meist gefleckte Fellzeichnung · lebt in Rudeln, oft in Gehegen und Wildparks.' },
  waschbaer: { key:'waschbaer', name:'Waschbär', sci:'Procyon lotor', rarity:'mammal', ...M,
    meaning:'Trillernde, zwitschernde und knurrende Laute sind <b style="color:var(--ink)">Kontakt- oder Drohverhalten</b> — ursprünglich aus Nordamerika, heute fest etabliert.',
    steckbrief:'40–60 cm Körperlänge · schwarze "Maske" ums Gesicht, geringelter Schwanz · nachtaktiv, klettert hervorragend.' },
  biber: { key:'biber', name:'Biber', sci:'Castor fiber', rarity:'mammal', ...M,
    meaning:'Ein lauter Schlag der platten Schwanzkelle aufs Wasser ist ein <b style="color:var(--ink)">Warnsignal</b> bei Störung — sonst meist leise.',
    steckbrief:'Bis 1,3 m inkl. Schwanz · größtes heimisches Nagetier · baut Dämme und Burgen, einst fast ausgerottet.' }
};
